import { neon } from '@neondatabase/serverless';
import { createHash, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';
const OTP_TTL_MS=5*60*1000, OTP_RESEND_COOLDOWN_MS=60*1000, MAX_OTP_ATTEMPTS=5, SESSION_TTL_MS=30*24*60*60*1000;
type UserRow={id:string;full_name:string;email:string;phone:string;email_verified:boolean};
function sqlClient(){const url=process.env.NEON_DATABASE_URL;if(!url)throw new Error('NEON_DATABASE_URL is not configured');return neon(url);}
async function ensureSchema(){const sql=sqlClient();await sql`CREATE TABLE IF NOT EXISTS public.bhs_users (id uuid PRIMARY KEY,full_name text NOT NULL,email text NOT NULL UNIQUE,phone text NOT NULL,password_hash text NOT NULL,email_verified boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS public.bhs_sessions (id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES public.bhs_users(id) ON DELETE CASCADE,token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS public.bhs_email_otps (id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES public.bhs_users(id) ON DELETE CASCADE,purpose text NOT NULL,otp_hash text NOT NULL,expires_at timestamptz NOT NULL,consumed_at timestamptz,attempts integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now())`;}
function normalizeEmail(v:unknown){return String(v||'').trim().toLowerCase();}
function hashSecret(v:string,salt=randomBytes(16).toString('hex')){return `${salt}:${scryptSync(v,salt,64).toString('hex')}`;}
function verifySecret(v:string,stored:string){const [salt,hex]=stored.split(':');if(!salt||!hex)return false;const actual=scryptSync(v,salt,64),expected=Buffer.from(hex,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
function hashToken(v:string){return createHash('sha256').update(v).digest('hex');}
function newOtp(){return String(Math.floor(100000+Math.random()*900000));}
function escapeHtml(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));}
async function sendOtpEmail(email:string,fullName:string,otp:string){const apiKey=process.env.RESEND_API_KEY;if(!apiKey)throw new Error('RESEND_API_KEY is not configured');const from=process.env.RESEND_FROM_EMAIL||"BH'S <onboarding@resend.dev>";const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:"Your BH'S verification code",html:`<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto"><h1>BH'S</h1><p>Hi ${escapeHtml(fullName)},</p><p>Your verification code is:</p><div style="font-size:32px;font-weight:700;letter-spacing:8px;padding:18px 0">${otp}</div><p>This code expires in 5 minutes and can only be used once.</p></div>`})});if(!r.ok)throw new Error('Email delivery failed');}
async function issueOtp(user:UserRow){const sql=sqlClient();const latest=await sql`SELECT created_at FROM public.bhs_email_otps WHERE user_id=${user.id} AND purpose='email_verification' ORDER BY created_at DESC LIMIT 1`;if(latest[0]&&Date.now()-new Date(String(latest[0].created_at)).getTime()<OTP_RESEND_COOLDOWN_MS)throw new Error('Please wait before requesting another code');const otp=newOtp(),expires=new Date(Date.now()+OTP_TTL_MS).toISOString();await sql`UPDATE public.bhs_email_otps SET consumed_at=COALESCE(consumed_at,${new Date().toISOString()}) WHERE user_id=${user.id} AND purpose='email_verification' AND consumed_at IS NULL`;await sql`INSERT INTO public.bhs_email_otps (id,user_id,purpose,otp_hash,expires_at) VALUES (${randomUUID()},${user.id},'email_verification',${hashSecret(otp)},${expires})`;await sendOtpEmail(user.email,user.full_name,otp);}
export async function signup(b:Record<string,unknown>){await ensureSchema();const fullName=String(b.fullName||'').trim(),email=normalizeEmail(b.email),phone=String(b.phone||'').trim(),password=String(b.password||'');if(fullName.length<2)throw new Error('Enter your full name');if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Enter a valid email address');if(phone.length<7)throw new Error('Enter a valid phone number');if(password.length<8)throw new Error('Password must be at least 8 characters');const sql=sqlClient(),existing=await sql`SELECT id,full_name,email,phone,email_verified FROM public.bhs_users WHERE email=${email} LIMIT 1` as UserRow[];if(existing[0]){if(existing[0].email_verified)throw new Error('An account already exists with this email');await issueOtp(existing[0]);return {needsVerification:true,email};}const id=randomUUID(),user={id,full_name:fullName,email,phone,email_verified:false} as UserRow;await sql`INSERT INTO public.bhs_users (id,full_name,email,phone,password_hash) VALUES (${id},${fullName},${email},${phone},${hashSecret(password)})`;try{await issueOtp(user);}catch(e){await sql`DELETE FROM public.bhs_users WHERE id=${id}`;throw e;}return {needsVerification:true,email};}
export async function resendOtp(emailInput:string){await ensureSchema();const email=normalizeEmail(emailInput),sql=sqlClient(),rows=await sql`SELECT id,full_name,email,phone,email_verified FROM public.bhs_users WHERE email=${email} LIMIT 1` as UserRow[],user=rows[0];if(!user)throw new Error('Account not found');if(user.email_verified)throw new Error('Account is already verified');await issueOtp(user);return {needsVerification:true,email};}
export async function verifyOtp(emailInput:string,otp:string){await ensureSchema();const email=normalizeEmail(emailInput);if(!/^\d{6}$/.test(otp))throw new Error('Enter the 6-digit code');const sql=sqlClient(),users=await sql`SELECT id,full_name,email,phone,email_verified FROM public.bhs_users WHERE email=${email} LIMIT 1` as UserRow[],user=users[0];if(!user)throw new Error('Account not found');const rows=await sql`SELECT id,otp_hash,expires_at,consumed_at,attempts FROM public.bhs_email_otps WHERE user_id=${user.id} AND purpose='email_verification' ORDER BY created_at DESC LIMIT 1`,record=rows[0] as {id:string;otp_hash:string;expires_at:string;consumed_at:string|null;attempts:number}|undefined;if(!record||record.consumed_at)throw new Error('That code is no longer valid. Request a new one.');if(new Date(record.expires_at).getTime()<=Date.now())throw new Error('That code has expired. Request a new one.');if(record.attempts>=MAX_OTP_ATTEMPTS)throw new Error('Too many attempts. Request a new code.');if(!verifySecret(otp,record.otp_hash)){await sql`UPDATE public.bhs_email_otps SET attempts=attempts+1 WHERE id=${record.id}`;throw new Error('Incorrect verification code');}await sql`UPDATE public.bhs_email_otps SET consumed_at=${new Date().toISOString()} WHERE id=${record.id}`;await sql`UPDATE public.bhs_users SET email_verified=true,updated_at=now() WHERE id=${user.id}`;return createSession(user);}
export async function login(emailInput:string,password:string){await ensureSchema();const email=normalizeEmail(emailInput),sql=sqlClient(),rows=await sql`SELECT id,full_name,email,phone,email_verified,password_hash FROM public.bhs_users WHERE email=${email} LIMIT 1`,row=rows[0] as (UserRow&{password_hash:string})|undefined;if(!row||!verifySecret(password,row.password_hash))throw new Error('Email or password is incorrect');if(!row.email_verified){await issueOtp(row);return {needsVerification:true,email};}return createSession(row);}
async function createSession(user:UserRow){const token=`bh_${randomBytes(32).toString('base64url')}`,sql=sqlClient(),expires=new Date(Date.now()+SESSION_TTL_MS).toISOString();await sql`DELETE FROM public.bhs_sessions WHERE user_id=${user.id} AND expires_at<now()`;await sql`INSERT INTO public.bhs_sessions (id,user_id,token_hash,expires_at) VALUES (${randomUUID()},${user.id},${hashToken(token)},${expires})`;return {token,user:{id:user.id,fullName:user.full_name,email:user.email,phone:user.phone}};}
export async function me(token:string){await ensureSchema();const sql=sqlClient(),rows=await sql`SELECT u.id,u.full_name,u.email,u.phone,u.email_verified FROM public.bhs_sessions s JOIN public.bhs_users u ON u.id=s.user_id WHERE s.token_hash=${hashToken(token)} AND s.expires_at>now() LIMIT 1` as UserRow[],user=rows[0];if(!user)throw new Error('Session expired');return {user:{id:user.id,fullName:user.full_name,email:user.email,phone:user.phone}};}
export async function logout(token:string){await ensureSchema();const sql=sqlClient();await sql`DELETE FROM public.bhs_sessions WHERE token_hash=${hashToken(token)}`;return {ok:true};}
